import {createHmac,timingSafeEqual,randomUUID,createHash} from 'node:crypto';
export type Session={sid:string;employeeId:string;role:'employee'|'manager';exp:number};
export type Message={role:'user'|'assistant';content:string};
export const COOKIE='gimme_session';
export function signValue(value:Record<string,unknown>,secret:string){const body=Buffer.from(JSON.stringify(value)).toString('base64url');return body+'.'+createHmac('sha256',secret).update(body).digest('base64url')}
export function verifyValue(token:string,secret:string,now=Math.floor(Date.now()/1000)):Record<string,unknown>|null{try{const [body,sig,...rest]=token.split('.');if(rest.length||!body||!sig)return null;const expected=createHmac('sha256',secret).update(body).digest();const actual=Buffer.from(sig,'base64url');if(actual.length!==expected.length||!timingSafeEqual(actual,expected))return null;const value=JSON.parse(Buffer.from(body,'base64url').toString());return typeof value.exp==='number'&&value.exp>now?value:null}catch{return null}}
export function secret(){const s=process.env.CHAT_SESSION_SECRET;if(!s||s.length<32)throw new Error('Secure chat sessions are not configured.');return s}
export function codeMatches(input:string,expected?:string){if(!expected||expected.length<12)return false;return timingSafeEqual(createHash('sha256').update(input).digest(),createHash('sha256').update(expected).digest())}
export function newSession(role:'employee'|'manager'):Session{return{sid:randomUUID(),employeeId:'SYN008078',role,exp:Math.floor(Date.now()/1000)+8*3600}}
export function getSession(req:Request):Session|null{try{const value=(req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(COOKIE+'='))?.slice(COOKIE.length+1);if(!value)return null;const s=verifyValue(value,secret());return s&&s.employeeId==='SYN008078'&&(s.role==='employee'||s.role==='manager')&&typeof s.sid==='string'?s as Session:null}catch{return null}}
export function requireSession(req:Request){const s=getSession(req);if(!s)throw new Error('Please unlock the assistant first.');return s}
export function sameOrigin(req:Request){const origin=req.headers.get('origin');if(!origin)return;const url=new URL(req.url);const host=req.headers.get('host')||url.host;const expected=url.protocol+'//'+host;if(origin!==expected)throw new Error('Cross-origin request rejected.')}
export function validateChatMessages(raw:unknown):Message[]{if(!Array.isArray(raw)||!raw.length||raw.length>12)throw new Error('Send between 1 and 12 conversation messages.');let total=0;const messages=raw.map(m=>{if(!m||!['user','assistant'].includes(m.role)||typeof m.content!=='string'||!m.content.trim()||m.content.length>4000||Object.keys(m).some(k=>!['role','content'].includes(k)))throw new Error('Invalid conversation message.');total+=m.content.length;return{role:m.role,content:m.content} as Message});if(total>18000||messages.at(-1)?.role!=='user')throw new Error('Conversation is too long or has no new question.');return messages}
export function validateLeaveInput(raw:unknown):{dates:string[];leaveCode:string;note:string}{if(!raw||typeof raw!=='object')throw new Error('Provide dates and leaveCode.');const o=raw as Record<string,unknown>;if(Object.keys(o).some(k=>!['dates','leaveCode','note'].includes(k)))throw new Error('Unknown leave input; employee identity is server-controlled.');if(!Array.isArray(o.dates)||!o.dates.length||o.dates.length>14||o.dates.some(d=>typeof d!=='string'||!/^2026-(09-(2[1-9]|30)|10-0[1-4])$/.test(d)))throw new Error('Select dates from 21 September to 4 October 2026.');if(!['AL','PE','LS'].includes(o.leaveCode as string))throw new Error('Choose AL, PE or LS.');if(o.note!==undefined&&(typeof o.note!=='string'||o.note.length>300))throw new Error('The note must be at most 300 characters.');return{dates:[...new Set(o.dates as string[])].sort(),leaveCode:o.leaveCode as string,note:(o.note as string)||''}}
export async function readBody(req:Request,max=24000){if(Number(req.headers.get('content-length'))>max)throw new Error('Request is too large.');const reader=req.body?.getReader();if(!reader)throw new Error('Missing request body.');const chunks:Uint8Array[]=[];let size=0;for(;;){const{done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();throw new Error('Request is too large.')}chunks.push(value)}return JSON.parse(Buffer.concat(chunks).toString())}

export function safeMessage(error:unknown){const m=error instanceof Error?error.message:'';return /^(Please unlock|Provide |Send between |Invalid conversation|Conversation is too|Select dates|Choose AL|The note must|Unknown leave input|Invalid tool arguments|Tool is not allowed|Department-wide|Assistant usage limit|Assistant is busy|Another request is being saved|Cross-origin request|Request is too large|Missing request|Foundry is not connected|Azure model capacity|The model connection failed|The model returned|The assistant reached|Choose a request confirmation|This confirmation expired|A request already covers|The request no longer|Request is not awaiting|Invalid decision|Confirm clinical|A decision reason|Manager access required|Request not found|Request was deleted|Choose a request awaiting|This option is no longer|This swap is no longer|Record a response|Choose acceptance|No pending invitation|This arrangement no longer)/.test(m)?m:'The service could not complete that check. Please try again shortly.'}
export function securityConfigured(){return (process.env.CHAT_SESSION_SECRET?.length||0)>=32}
