import raw from '@/data/workforce.json';
import policyRaw from '@/data/policies.json';
import type {Workforce,PolicyIndex,Booking} from '@/lib/workforce-types';
import {findAvailableSwaps,assessWithRequests,afterSwap} from '@/lib/workforce-engine';
import {requireSession,sameOrigin,readBody,safeMessage} from '@/server/chat-security';
import {listBookings,saveBooking,audit,withEmployeeLock} from '@/server/chat-store';
import {getStaffingFloors,withStaffingChecks} from '@/server/staffing-plan';
export const runtime='nodejs';
export const dynamic='force-dynamic';
const w=raw as Workforce,p=policyRaw as unknown as PolicyIndex;
function manager(req:Request){const s=requireSession(req);if(s.role!=='manager')throw new Error('Manager access required.');return s}
const available=(b:Booking,all:Booking[])=>findAvailableSwaps(w,p,b.dates,all,b.id);
export async function GET(req:Request){try{const s=manager(req),all=await listBookings(s.employeeId),b=all.find(r=>r.id===new URL(req.url).searchParams.get('requestId'));if(!b)throw new Error('Request not found.');const floors=await getStaffingFloors();const options=available(b,all).map(o=>withStaffingChecks(o,b.dates,all.filter(r=>r.id!==b.id),floors));return Response.json({options:options.sort((a,c)=>Number(c.id===b.swap?.id)-Number(a.id===b.swap?.id)).slice(0,5),invitation:b.swapInvitation},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({message:safeMessage(e)},{status:400})}}
export async function POST(req:Request){try{sameOrigin(req);const s=manager(req),body=await readBody(req,3000);return await withEmployeeLock(s.employeeId,async()=>{const all=await listBookings(s.employeeId),b=all.find(r=>r.id===body.requestId);if(!b||b.status!=='manager-review')throw new Error('Choose a request awaiting manager review.');const swap=available(b,all).find(o=>o.id===body.swapId);if(!swap)throw new Error('This option is no longer available. Refresh the options.');if(b.swapInvitation?.status==='pending')throw new Error('Record a response to the current invitation before sending another.');const at=new Date().toISOString();const message=`Could you ${swap.kind==='swap'?'swap':'cover'} Sarah’s ${swap.outgoing.date} ${swap.outgoing.start}–${swap.outgoing.end} duty? ${swap.returnShift?`Sarah would work your ${swap.returnShift.date} ${swap.returnShift.start}–${swap.returnShift.end} duty.`:'Your current duties would remain unchanged.'} Please let your manager know whether this works for you. Approval is still required.`;const request:Booking={...b,swap,assessment:afterSwap(assessWithRequests(w,p,b.dates,b.leaveCode,all.filter(r=>r.id!==b.id)),swap),message,swapInvitation:{id:crypto.randomUUID(),recipientId:swap.employeeId,message,status:'pending',createdAt:at},events:[...b.events,{at,label:'Swap invitation sent in app',detail:`Addressed to ${swap.employeeId}. No external message sent; awaiting response.`}]};await saveBooking(request);await audit(s.employeeId,'swap-invitation',{requestId:b.id,recipientId:swap.employeeId});return Response.json({request,message:'Invitation saved in the colleague inbox preview.'})})}catch(e){return Response.json({message:safeMessage(e)},{status:400})}}
export async function PATCH(req:Request){try{sameOrigin(req);const s=manager(req),body=await readBody(req,1000);if(body.status!=='accepted'&&body.status!=='declined')throw new Error('Choose acceptance or decline.');return await withEmployeeLock(s.employeeId,async()=>{const all=await listBookings(s.employeeId),b=all.find(r=>r.id===body.requestId);if(!b||b.status!=='manager-review'||!b.swapInvitation||b.swapInvitation.status!=='pending')throw new Error('No pending invitation for this request.');if(body.status==='accepted'&&!available(b,all).some(o=>o.id===b.swap?.id))throw new Error('This arrangement no longer passes the roster checks.');const at=new Date().toISOString(),declined=body.status==='declined';const request:Booking={...b,swap:declined?null:b.swap,assessment:declined?assessWithRequests(w,p,b.dates,b.leaveCode,all.filter(r=>r.id!==b.id)):b.assessment,swapInvitation:{...b.swapInvitation,status:body.status,respondedAt:at},events:[...b.events,{at,label:`Manager recorded colleague ${body.status}`,detail:'Recorded by the manager; not an authenticated colleague response. Clinical verification and approval remain required.'}]};await saveBooking(request);await audit(s.employeeId,'swap-response-recorded',{requestId:b.id,status:body.status});return Response.json({request,message:'Response recorded. Leave is not yet approved.'})})}catch(e){return Response.json({message:safeMessage(e)},{status:400})}}
