import {beforeEach,describe,it,expect} from 'vitest';
import {executeTool} from '../src/server/chat-tools';
import {POST as confirm} from '../src/app/api/chat/actions/route';
import {PATCH as approve} from '../src/app/api/chat/requests/route';
import {saveStaffingFloors} from '../src/server/staffing-plan';
import {GET,POST,PATCH} from '../src/app/api/chat/swaps/route';
import {signValue} from '../src/server/chat-security';
import {listBookings} from '../src/server/chat-store';
const key='swap-test-secret-'.repeat(4);
const employee={sid:'swap-test',employeeId:'SYN008078',role:'employee' as const,exp:9999999999};
const manager={...employee,role:'manager' as const};
function req(path:string,method:string,body?:unknown,role:'employee'|'manager'='manager') {return new Request('http://localhost'+path,{method,headers:{Origin:'http://localhost','Content-Type':'application/json',Cookie:'gimme_session='+signValue(role==='manager'?manager:employee,key)},...(body?{body:JSON.stringify(body)}:{})})}
beforeEach(()=>{process.env.CHAT_SESSION_SECRET=key;process.env.CHAT_LOCAL_STORE=process.cwd()+'/.release-local/test-swaps-'+crypto.randomUUID()+'.json';delete process.env.AZURE_STORAGE_CONNECTION_STRING});
async function submit(){const result=await executeTool('find_shift_options',{dates:['2026-09-21'],leaveCode:'AL'},employee);expect(result.swapChoices!.length).toBeGreaterThan(0);expect(await listBookings(employee.employeeId)).toEqual([]);const choice=result.swapChoices![0];const response=await confirm(req('/api/chat/actions','POST',{proposalId:choice.proposal.id},'employee'));expect(response.status).toBe(200);return {booking:(await response.json()).request,choice};}
describe('chat to manager swap handoff',()=>{
 it('preserves the confirmed swap and makes fresh options visible to managers',async()=>{const {booking,choice}=await submit();expect(booking.swap.id).toBe(choice.option.id);const response=await GET(req('/api/chat/swaps?requestId='+booking.id,'GET'));expect(response.status).toBe(200);expect((await response.json()).options[0].id).toBe(choice.option.id)});
 it('saves a recipient-addressed invitation and records a response without approving leave',async()=>{const {booking,choice}=await submit();const response=await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id}));expect(response.status).toBe(200);const sent=(await response.json()).request;expect(sent.swapInvitation.recipientId).toBe(choice.option.employeeId);expect(sent.swapInvitation.status).toBe('pending');const replied=await PATCH(req('/api/chat/swaps','PATCH',{requestId:booking.id,status:'accepted'}));expect(replied.status).toBe(200);const saved=(await replied.json()).request;expect(saved.swapInvitation.status).toBe('accepted');expect(saved.status).toBe('manager-review');expect(saved.events.at(-1).detail).toContain('not an authenticated')});
 it('rejects employee invitation sends, invented options and repeated pending invitations',async()=>{const {booking,choice}=await submit();expect((await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id},'employee'))).status).toBe(400);expect((await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:'invented'}))).status).toBe(400);expect((await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id}))).status).toBe(200);expect((await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id}))).status).toBe(400)});
 it('decline clears the proposed swap so another option can be chosen',async()=>{const {booking,choice}=await submit();await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id}));const response=await PATCH(req('/api/chat/swaps','PATCH',{requestId:booking.id,status:'declined'}));const b=(await response.json()).request;expect(b.swap).toBeNull();expect(b.swapInvitation.status).toBe('declined');expect(b.assessment.hours).toBe(8)});
 it('blocks approval while consent is pending or a configured minimum is unmet',async()=>{const {booking,choice}=await submit();await POST(req('/api/chat/swaps','POST',{requestId:booking.id,swapId:choice.option.id}));const decision={id:booking.id,status:'approved',verified:true,note:''};expect((await approve(req('/api/chat/requests','PATCH',decision))).status).toBe(400);await PATCH(req('/api/chat/swaps','PATCH',{requestId:booking.id,status:'accepted'}));await saveStaffingFloors({'2026-09-21|0|Registered Nurse':30});const blocked=await approve(req('/api/chat/requests','PATCH',decision));expect(blocked.status).toBe(400);expect((await blocked.json()).message).toContain('staffing minimum');expect((await listBookings(employee.employeeId))[0].status).toBe('manager-review')});

});
