import raw from '../src/data/workforce.json';
import type {Workforce} from '../src/lib/workforce-types';
import {beforeEach,describe,it,expect} from 'vitest';
import {executeTool} from '../src/server/chat-tools';
import {POST as submit} from '../src/app/api/chat/actions/route';
import {POST as invite,GET as managerOptions} from '../src/app/api/chat/swaps/route';
import {GET,POST} from '../src/app/api/teams-preview/route';
import {PATCH as decision} from '../src/app/api/chat/requests/route';
import {signValue} from '../src/server/chat-security';
import {swapWorkImpact} from '../src/server/swap-coordination';
import {listBookings} from '../src/server/chat-store';
const key='teams-preview-test-key'.repeat(3);
const employee={sid:'teams-test',employeeId:'SYN008078',role:'employee' as const,exp:9999999999},manager={...employee,role:'manager' as const};
function req(path:string,method:string,body?:unknown,role='manager'){return new Request('http://localhost'+path,{method,headers:{Origin:'http://localhost','Content-Type':'application/json',Cookie:'gimme_session='+signValue(role==='manager'?manager:employee,key)},...(body?{body:JSON.stringify(body)}:{})})}
beforeEach(()=>{process.env.CHAT_SESSION_SECRET=key;process.env.CHAT_LOCAL_STORE=process.cwd()+'/.release-local/test-teams-'+crypto.randomUUID()+'.json';delete process.env.AZURE_STORAGE_CONNECTION_STRING});
async function setup(){const tool=await executeTool('find_shift_options',{dates:['2026-09-21'],leaveCode:'AL'},employee);const choice=tool.swapChoices![0];const b=(await (await submit(req('/api/chat/actions','POST',{proposalId:choice.proposal.id},'employee'))).json()).request;expect((await invite(req('/api/chat/swaps','POST',{requestId:b.id,swapId:choice.option.id}))).status).toBe(200);const row=(await (await GET(req('/api/teams-preview?requestId='+b.id,'GET'))).json()).requests[0];return {row,choice};}
describe('Teams visual response lifecycle',()=>{
 it('shows roster-derived hours and rests and rejects employee browsing',async()=>{const {row,choice}=await setup();expect(row.recipientName).toBeTruthy();expect(row.impact).toEqual(swapWorkImpact(choice.option));expect(row.impact.hoursAfter).toBe(choice.option.candidateHoursAfter);expect(row.replyToken).toBeTruthy();expect((await GET(req('/api/teams-preview','GET',undefined,'employee'))).status).toBe(400)});
 it('accepts one scoped response and leaves final approval to the manager',async()=>{const {row}=await setup();const response=await POST(req('/api/teams-preview','POST',{token:row.replyToken,status:'accepted',reason:''}));expect(response.status).toBe(200);const b=(await response.json()).request;expect(b.status).toBe('manager-review');expect(b.swapInvitation.responseSource).toBe('teams-preview');expect(b.swapInvitation.status).toBe('accepted');expect((await POST(req('/api/teams-preview','POST',{token:row.replyToken,status:'declined',reason:'Changed mind'}))).status).toBe(400)});
 it('requires a decline reason, returns it to the manager and suggests alternatives on manager decline',async()=>{const {row}=await setup();expect((await POST(req('/api/teams-preview','POST',{token:row.replyToken,status:'declined',reason:''}))).status).toBe(400);const response=await POST(req('/api/teams-preview','POST',{token:row.replyToken,status:'declined',reason:'Family commitment on Monday'}));expect(response.status).toBe(200);const b=(await response.json()).request;expect(b.swap).toBeNull();expect(b.swapInvitation.option).toBeTruthy();expect(b.status).toBe('manager-review');const review=await (await managerOptions(req('/api/chat/swaps?requestId='+b.id,'GET'))).json();expect(review.decisionDraft).toContain('Family commitment');expect(review.alternatives.length).toBeGreaterThan(0);const decided=await decision(req('/api/chat/requests','PATCH',{id:b.id,status:'declined',note:review.decisionDraft}));expect(decided.status).toBe(200);const saved=(await decided.json()).request;expect(saved.alternativeDates.length).toBeGreaterThan(0);expect(saved.managerNote).toContain('Family commitment')});
 it('rejects tampering and cross-origin replies without changing invitation',async()=>{const {row}=await setup();expect((await POST(req('/api/teams-preview','POST',{token:row.replyToken+'x',status:'accepted'}))).status).toBe(400);const request=req('/api/teams-preview','POST',{token:row.replyToken,status:'accepted'});request.headers.set('Origin','https://other.example');expect((await POST(request)).status).toBe(400);expect((await listBookings(employee.employeeId))[0].swapInvitation?.status).toBe('pending')});
 it('calculates rest across overnight dates from neighbouring duty endpoints',async()=>{const {choice}=await setup(),option=choice.option;const shift={...option.outgoing,employeeId:option.employeeId};const w={...raw,shifts:[{...shift,id:'previous',date:'2026-09-19',start:'21:00',end:'07:00'},{...shift,id:'next',date:'2026-09-22',start:'07:00',end:'15:00'}]} as Workforce;const impact=swapWorkImpact(option,w);expect(impact.restBeforeHours).toBe(24);expect(impact.restAfterHours).toBe(15.5);expect(impact.restBeforeMinimumHours).toBe(20);expect(impact.restAfterMinimumHours).toBe(9.5)});

});
