import {describe,it,expect} from 'vitest';
import {assess,findSwaps,interval,latestBalances,assessWithRequests,findAvailableSwaps,afterSwap,projectedRoster,submitForReview,canApprove} from '../src/lib/workforce-engine';
import type {Workforce,PolicyIndex,Shift,Booking} from '../src/lib/workforce-types';
const shift=(id:string,employeeId:string,date:string,start='07:00',end='15:30'):Shift=>({id,employeeId,date,start,end,unit:'U',unitName:'Emergency',mealMinutes:30,netHours:8,payPeriodStart:'2026-09-21',payPeriodEnd:'2026-10-04',workCode:'D8'});
const data:Workforce={period:{start:'2026-09-21',end:'2026-10-04',decisionDate:'2026-09-19'},employeeId:'A',unit:'U',employees:['A','B'].map(id=>({id,role:'Registered Nurse',rate:'R1',group:'NURSING',unit:'U',unitName:'Emergency',contractHours:76,occupancy:'SUBSTANTIVE',contractStart:'2026-01-01',contractEnd:'2027-01-01'})),balances:[{employeeId:'A',code:'AL',type:'Annual leave',effectiveDate:'2026-09-17',remainingHours:80,untakenHours:80,bookedHours:0,excess:false}],shifts:[shift('a','A','2026-09-21'),shift('b','B','2026-09-24')],leave:[],sources:[],quality:{},notes:[]};
const policies={documents:[],rules:{minimumRestHours:9.5,ratios:[]}} as unknown as PolicyIndex;
describe('fortnight workforce workflow',()=>{
it('uses current balances and deducts net roster hours',()=>{const d={...data,balances:[...data.balances,{...data.balances[0],effectiveDate:'2026-09-24',remainingHours:999}]};expect(latestBalances(d,'A')[0].remainingHours).toBe(80);expect(assess(d,policies,['2026-09-21'],'AL').balanceRemaining).toBe(72)});
it('rejects no selection and overlapping recorded leave',()=>{expect(assess(data,policies,[],'AL').canProceed).toBe(false);expect(assess({...data,leave:[{employeeId:'A',start:'2026-09-21',end:'2026-09-21',code:'AL',type:'Annual',hours:8,status:'APPROVED',recordType:'LEAVE'}]},policies,['2026-09-21'],'AL').canProceed).toBe(false)});
it('models overnight intervals',()=>expect((interval(shift('n','B','2026-09-21','21:00','07:00'))[1]-interval(shift('n','B','2026-09-21','21:00','07:00'))[0])/3600000).toBe(10));
it('offers a bilateral swap only when both people can take the other shift',()=>{expect(findSwaps(data,policies,['2026-09-21']).some(s=>s.kind==='swap')).toBe(true);const blocked={...data,shifts:[...data.shifts,shift('x','A','2026-09-24')]};expect(findSwaps(blocked,policies,['2026-09-21']).some(s=>s.kind==='swap')).toBe(false)});
it('rejects night-to-day changes without twenty hours rest',()=>{const d={...data,shifts:[...data.shifts,shift('n','B','2026-09-20','21:00','07:00')]};expect(findSwaps(d,policies,['2026-09-21'])).toHaveLength(0)});
it('does not substitute another role or claim patient ratios verified',()=>{expect(findSwaps({...data,employees:data.employees.map(e=>e.id==='B'?{...e,role:'Enrolled Nurse'}:e)},policies,['2026-09-21'])).toHaveLength(0);expect(assess(data,policies,['2026-09-21'],'AL').checks.find(c=>c.id==='mix')?.status).toBe('warning')});
});

const booking=(overrides:Partial<Booking>={}):Booking=>({id:'request1',employeeId:'A',leaveCode:'AL',leaveType:'Annual leave',dates:['2026-09-21'],note:'',assessment:assess(data,policies,['2026-09-21'],'AL'),status:'assessed',swap:null,message:'',managerNote:'',createdAt:'2026-09-19T00:00:00Z',events:[],...overrides});
describe('request coordination regressions',()=>{
 it('reserves local balance across independent dates',()=>expect(assessWithRequests(data,policies,['2026-09-24'],'AL',[booking()]).balance?.remainingHours).toBe(72));
 it('reserves a proposed colleague and their return day',()=>{const o=findSwaps(data,policies,['2026-09-21'])[0];expect(findAvailableSwaps(data,policies,['2026-09-21'],[booking({swap:o})])).toHaveLength(0)});
 it('checks overnight overlap against next-day leave',()=>{const d={...data,shifts:[shift('a','A','2026-09-21','21:00','07:00')],leave:[{employeeId:'B',start:'2026-09-22',end:'2026-09-22',hours:8,code:'AL',type:'Annual',status:'APPROVED',recordType:'Leave'}]};expect(findSwaps(d,policies,['2026-09-21'])).toHaveLength(0)});
 it('discounts only a real equal-hour swap from leave',()=>{const o=findSwaps(data,policies,['2026-09-21']).find(o=>o.kind==='swap')!;expect(afterSwap(booking().assessment,o).balanceRemaining).toBe(80)});
 it('drops declined cover and records the actual submission date',()=>{const o=findSwaps(data,policies,['2026-09-21'])[0];const b=booking({swap:o,status:'colleague-declined',assessment:afterSwap(booking().assessment,o)});const submitted=submitForReview(data,policies,b,[b],'2026-09-20T12:00:00Z')!;expect(submitted.swap).toBeNull();expect(submitted.assessment.balanceRemaining).toBe(72);expect(submitted.submittedAt).toBe('2026-09-20T12:00:00Z');expect(submitted.events.at(-1)?.detail).not.toContain('accepted')});
 it('requires manager verification and reflects approved bilateral roster changes',()=>{const o=findSwaps(data,policies,['2026-09-21']).find(o=>o.kind==='swap')!;const b=booking({swap:o,status:'manager-review'});expect(canApprove(b,false)).toBe(false);expect(canApprove(b,true)).toBe(false);expect(canApprove({...b,swapInvitation:{id:'invite',recipientId:o.employeeId,message:'Swap?',status:'accepted',createdAt:'2026-09-20'}},true)).toBe(true);const projected=projectedRoster(data,[{...b,status:'approved'}]);expect(projected.find(s=>s.id==='a')?.employeeId).toBe('B');expect(projected.find(s=>s.id==='b')?.employeeId).toBe('A');expect(projected).toHaveLength(2)});
 it('does not treat an unknown instrument as ANF',()=>expect(findSwaps({...data,employees:data.employees.map(e=>({...e,industrialInstrument:'AMA_2024'}))},policies,['2026-09-21'])).toHaveLength(0));
});
