'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,Save,Check} from 'lucide-react';
import raw from '@/data/workforce.json';
import type {Workforce} from '@/lib/workforce-types';
import {roles,bands,coverage,floorKey,applyFloors,type Floors} from '@/lib/staffing-requirements';
import './staffing-requirements.css';
const w=raw as Workforce;
const dates=Array.from({length:14},(_,i)=>new Date(Date.parse(w.period.start+'T12:00:00Z')+i*86400000).toISOString().slice(0,10));
const label=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'short'});
export default function StaffingRequirements(){
 const [date,setDate]=useState(dates[0]),[band,setBand]=useState(0),[floors,setFloors]=useState<Floors>({}),[draft,setDraft]=useState<(number|null)[]>(roles.map(()=>null)),[scope,setScope]=useState('shift'),[notice,setNotice]=useState('');
 const own=w.shifts.filter(s=>s.employeeId===w.employeeId&&dates.includes(s.date));
 const [leaveDate,setLeaveDate]=useState(dates[0]);const shift=own.find(s=>s.date===leaveDate)!;
 useEffect(()=>{const load=()=>fetch('/api/department/staffing',{cache:'no-store'}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.message);setFloors(body.floors);setNotice('')}).catch(e=>setNotice(e.message||'Could not load staffing settings.'));void load();window.addEventListener('gimme:session',load);return()=>window.removeEventListener('gimme:session',load)},[]);
 useEffect(()=>{setDraft(roles.map(role=>floors[floorKey(date,band,role)]??null))},[date,band,floors]);
 const before=roles.map(r=>coverage(w,date,band,r)),after=roles.map(r=>coverage(w,date,band,r,shift.id));
 const shortages=roles.flatMap((r,i)=>draft[i]!==null&&after[i]<draft[i]!?[{role:r,need:draft[i]!,have:after[i],before:before[i]}]:[]);
 const save=async()=>{const f=applyFloors(floors,draft,dates,date,band,scope);try{const response=await fetch('/api/department/staffing',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({floors:f})});const body=await response.json();if(!response.ok)throw new Error(body.message);setFloors(body.floors);setNotice('Staffing plan saved. New chatbot checks use these minimums.')}catch(e){setNotice(e instanceof Error?e.message:'Could not save staffing settings.')}};
 return <div className="staffing-ui"><div className="isolation">Saved minimums are shared with the chatbot and used in new leave and cover checks. Your manager still approves each request.</div>

 <section className="period"><div><CalendarDays size={21}/><div><small>PLANNING FORTNIGHT</small><b>21 September – 4 October 2026</b></div></div><span>14 days · 42 shift windows</span></section>
 <div className="date-strip">{dates.map(d=><button key={d} className={date===d?'selected':''} onClick={()=>setDate(d)}><small>{new Date(d+'T12:00Z').toLocaleDateString('en-AU',{weekday:'short'})}</small><b>{Number(d.slice(-2))}</b><i className={roles.some(r=>floors[floorKey(d,band,r)]!=null)?'configured':''}/></button>)}</div>
 <section className="floor-card"><div className="section-top"><div><h2>Minimum clinicians per shift</h2><p>{label(date)} · Exact role categories · Minimum concurrent coverage</p></div><div className="segmented">{bands.map((b,i)=><button key={b.name} className={band===i?'selected':''} onClick={()=>setBand(i)}>{b.name}<small>{b.start}–{b.end}</small></button>)}</div></div>
 <div className="column-hint"><span>10 clinical roles · Set each minimum independently</span><span>Scroll across to see all roles →</span></div><div className="sliders" tabIndex={0} role="region" aria-label="Staffing minimums for ten roles, scroll horizontally">{roles.map((role,i)=><div key={role} className={'role-column '+(draft[i]!==null&&after[i]<draft[i]!?' short':'')}><span className="role-number">{String(i+1).padStart(2,'0')}</span><h3>{role}</h3><div className={'floor-value'+(draft[i]===null?' unset':'')}>{draft[i]??'Not set'}<small>MINIMUM</small></div><input aria-label={role+' minimum slider'} type="range" min="0" max="30" value={draft[i]??0} onChange={e=>setDraft(draft.map((x,j)=>j===i?Number(e.target.value):x))}/><input aria-label={role+' minimum'} type="number" min="0" max="30" placeholder="Not set" value={draft[i]??''} onChange={e=>setDraft(draft.map((x,j)=>j===i?(e.target.value===''?null:Math.max(0,Math.min(30,Math.floor(Number(e.target.value))))):x))}/><div className="counts"><span>Rostered <b>{before[i]}</b></span><span>After leave <b>{after[i]}</b></span></div></div>)}</div>
 <div className="apply-bar"><label>Apply these 10 floors to<select value={scope} onChange={e=>setScope(e.target.value)}><option value="shift">This shift only</option><option value="day">All shifts on this day</option><option value="matching">This shift across the fortnight</option><option value="fortnight">Every shift in the fortnight</option></select></label><button className="text-btn" onClick={()=>setDraft(roles.map(()=>null))}>Clear editor</button><button className="primary" onClick={save}><Save size={16}/>Save staffing plan</button></div></section>
 <section className="impact"><div><span className="eyebrow">TRY A LEAVE REQUEST</span><h2>What happens if Sarah takes leave?</h2><label>Remove Sarah’s rostered duty <select value={leaveDate} onChange={e=>{setLeaveDate(e.target.value);setDate(e.target.value);setBand(own.find(s=>s.date===e.target.value)!.start<'12:00'?0:1)}}>{own.map(s=><option key={s.id} value={s.date}>{label(s.date)} · {s.start}–{s.end}</option>)}</select></label><p>Compares the selected shift window above. Counts use distinct staff present throughout each interval; recorded absences are excluded.</p></div><div className={'impact-result '+(shortages.length?'blocked':'')}><span>{shortages.length?'COVERAGE REQUIRED':draft.every(x=>x===null)?'REQUIREMENTS NOT SET':'CONFIGURED FLOORS MET'}</span><h3>{shortages.length?shortages[0].role+': '+shortages[0].have+' / '+shortages[0].need:'Ready to explore the impact'}</h3><p>{shortages.length?'This window is '+(shortages[0].need-shortages[0].have)+' below your minimum'+(shortages[0].before<shortages[0].need?' before leave as well.':' after leave.'):'Set your staffing floors to test this request. Meeting a floor does not approve leave.'}</p></div></section>
 <p className="basis">Manager-defined operating floors, not statutory ratios. This preview uses the roster snapshot. The chatbot also considers saved requests. Verified competency, patient demand and break coverage still need review. Medical specialties are not interchangeable. Unset means unknown, not zero.</p>
 {notice&&<div className="toast" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}</div>
}
