'use client';
import {useEffect,useState} from 'react';
import {Bell,ArrowRight,CalendarDays} from 'lucide-react';
import type {LeaveInvitation} from '@/lib/leave-invitation';
const fmt=(d:string)=>new Date(d+'T12:00:00Z').toLocaleDateString('en-AU',{day:'numeric',month:'short'});
export default function EmployeeInbox({onDates}:{onDates:(dates:string[],code:string)=>void}){
 const [items,setItems]=useState<LeaveInvitation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/department/invitations',{cache:'no-store'});if(!active)return;if(!r.ok){setItems([]);return}const b=await r.json();if(active)setItems(b.invitations||[])}catch{if(active)setError('Unable to load messages.')}};void load();window.addEventListener('gimme:server-request',load);return()=>{active=false;window.removeEventListener('gimme:server-request',load)}},[]);
 async function reply(item:LeaveInvitation,status:'interested'|'discuss'){
  setBusy(item.id);setError('');try{const r=await fetch('/api/department/invitations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status})});const b=await r.json();if(!r.ok)throw new Error(b.message);setItems(p=>p.map(i=>i.id===item.id?b.invitation:i));window.dispatchEvent(new CustomEvent('gimme:server-request'));if(status==='interested'&&item.dates.length)onDates(item.dates,item.leaveCode)}catch(e){setError(e instanceof Error?e.message:'Unable to reply.')}finally{setBusy(null)}
 }
 if(!items.length&&!error)return null;
 return <section className="wf-card wf-inbox wf-inbox-compact"><div className="wf-section-head"><h2><Bell size={19}/>From your manager</h2><span className="wf-pill">{items.filter(i=>i.status==='invited').length} new</span></div>{items.map(i=><article key={i.id}><div className="wf-invitation-row"><div><h3>Plan your {i.leaveCode==='LS'?'long service':'annual'} leave</h3>{i.dates.length>0?<p className="wf-short-date"><CalendarDays size={16}/>{fmt(i.dates[0])}{i.dates.at(-1)!==i.dates[0]?' – '+fmt(i.dates.at(-1)!):''}<span>· {i.hours} hours</span></p>:<p>Your manager would like to agree dates for a break.</p>}{i.status!=='invited'&&<small>{i.status==='discuss'?'Your manager knows you would like to discuss.':'You are interested in these dates.'}</small>}</div><div className="wf-actions"><button className="wf-primary" disabled={!!busy} onClick={()=>void reply(i,'interested')}>{i.dates.length?'Review dates':'Plan leave'}<ArrowRight size={16}/></button><button className="wf-secondary" disabled={!!busy||i.status==='discuss'} onClick={()=>void reply(i,'discuss')}>Discuss</button></div></div><details className="wf-message-details"><summary>Message & details</summary><p>{i.message}</p><p>{i.staffingNote}</p><small>{Math.round(i.remainingHours)}h remaining if agreed. This invitation is not an approval.</small></details></article>)}{error&&<p role="alert" className="wf-error">{error}</p>}</section>;
}
