'use client';
import {useEffect,useState} from 'react';
import {Bell,ArrowRight,MessageCircle,CalendarDays} from 'lucide-react';
import type {LeaveInvitation} from '@/lib/leave-invitation';
export default function EmployeeInbox({onDates}:{onDates:(dates:string[],code:string)=>void}){
 const [items,setItems]=useState<LeaveInvitation[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState<string|null>(null);
 useEffect(()=>{let active=true;const load=async()=>{try{const r=await fetch('/api/department/invitations',{cache:'no-store'});if(!active)return;if(!r.ok){setItems([]);return}const b=await r.json();if(active)setItems(b.invitations||[])}catch{if(active)setError('Unable to load messages.')}};void load();window.addEventListener('gimme:server-request',load);return()=>{active=false;window.removeEventListener('gimme:server-request',load)}},[]);
 async function reply(item:LeaveInvitation,status:'interested'|'discuss'){
  setBusy(item.id);setError('');try{const r=await fetch('/api/department/invitations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,status})});const b=await r.json();if(!r.ok)throw new Error(b.message);setItems(p=>p.map(i=>i.id===item.id?b.invitation:i));window.dispatchEvent(new CustomEvent('gimme:server-request'));if(status==='interested'&&item.dates.length)onDates(item.dates,item.leaveCode)}catch(e){setError(e instanceof Error?e.message:'Unable to reply.')}finally{setBusy(null)}
 }
 if(!items.length&&!error)return null;
 return <section className="wf-card wf-inbox"><div className="wf-section-head"><h2><Bell size={21}/>Messages from your manager</h2><span className="wf-pill">{items.filter(i=>i.status==='invited').length} new</span></div>{items.map(i=><article key={i.id}><div className="wf-section-head"><div><small>{i.sender} · Leave planning</small><h3>Let’s make room for your next break</h3></div><span className="wf-pill">{i.status==='invited'?'Invitation':i.status==='discuss'?'Discussion requested':'Interested in these dates'}</span></div><p>{i.message}</p>{i.dates.length>0&&<div className="wf-inbox-dates"><CalendarDays size={19}/><strong>{i.dates[0]} – {i.dates.at(-1)}</strong><span>{i.hours}h suggested · {Math.round(i.remainingHours*10)/10}h projected balance</span></div>}<p className="wf-muted">{i.staffingNote}</p><div className="wf-actions"><button className="wf-primary" disabled={!!busy} onClick={()=>void reply(i,'interested')}> {i.dates.length?'Review suggested dates':'I’d like to plan leave'}<ArrowRight size={17}/></button><button className="wf-secondary" disabled={!!busy} onClick={()=>void reply(i,'discuss')}><MessageCircle size={17}/>Discuss with my manager</button></div><small>This is a planning invitation. Your leave is not booked or approved.</small></article>)}{error&&<p role="alert" className="wf-error">{error}</p>}</section>;
}
