'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowRight,ArrowLeft,CalendarDays,Check,CheckCircle2,ChevronRight,Clock,Heart,Leaf,Users,X,LoaderCircle,ShieldCheck,Sun,Activity,BookOpen,Repeat2,Send,Home,ClipboardList,AlertCircle,Database} from 'lucide-react';
import raw from '@/data/workforce.json';
import policyRaw from '@/data/policies.json';
import type {Workforce,PolicyIndex,Booking,SwapOption,Assessment,Check as CheckType} from '@/lib/workforce-types';
import {assess,findSwaps,mine,latestBalances,datesBetween,round,canApprove,assessWithRequests,findAvailableSwaps,projectedRoster,afterSwap,submitForReview} from '@/lib/workforce-engine';
import './workforce.css';
const data=raw as Workforce, policies=policyRaw as unknown as PolicyIndex;
const me=data.employees.find(e=>e.id===data.employeeId)!;
const days=datesBetween(data.period.start,data.period.end), balances=latestBalances(data,me.id),shifts=mine(data);
const fmt=(d:string,opts:Intl.DateTimeFormatOptions={day:'numeric',month:'short'})=>new Date(d+'T12:00:00').toLocaleDateString('en-AU',opts);
const unitLabel=(s:string)=>s.replace(/SU\d+\s*-\s*/,'').replace(/Synthetic\s*/,'');
const title=(s:string)=>s.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const leaveName=(code:string)=>code==='AL'?'Annual leave':code==='PE'?'Personal leave':code==='LS'?'Long service leave':balances.find(b=>b.code===code)?.type||code;
const name=(id:string)=>{if(id===me.id)return 'Sarah Chen';const i=Math.max(0,data.employees.findIndex(e=>e.id===id));return ['Emily','James','Priya','Daniel','Amelia','Oliver','Chloe','Ethan','Grace','Liam','Sophie','Noah','Aisha','Lucas','Isla','Mia'][i%16]+' '+['Zhang','Wilson','Kumar','Taylor','Nguyen','Patel','Williams','Brown','Martin','Lee','Thomas','Clarke','Harris','Wong','Walker'][Math.floor(i/16)%15]};
const statusName=(s:string)=>({'assessed':'Checks complete','awaiting-colleague':'Awaiting colleague','colleague-declined':'Colleague unavailable','manager-review':'Manager review','approved':'Approved','declined':'Declined','changes-requested':'Changes requested'} as Record<string,string>)[s]||s;
const policy=(id?:string)=>policies.documents.find(d=>d.id===id);
const now=()=>new Date().toISOString();
const dateOf=(iso:string)=>iso.slice(0,10);
const due=(b:Booking)=>{const d=new Date(b.submittedAt||b.createdAt);d.setDate(d.getDate()+14);return d.toLocaleDateString('en-AU',{day:'numeric',month:'short'})};
const event=(label:string,detail:string)=>({at:now(),label,detail});
function CheckRows({checks}:{checks:CheckType[]}){return <div className="wf-checks">{checks.map(c=><div key={c.id} className={`wf-check ${c.status}`}><span>{c.status==='pass'?<CheckCircle2 size={19}/>:<AlertCircle size={19}/>}</span><div><strong>{c.label}</strong><p>{c.detail}</p>{policy(c.policyId)?<a href={policy(c.policyId)!.pdfUrl||policy(c.policyId)!.url} target="_blank" rel="noreferrer">{c.source} ↗</a>:<small>{c.source}</small>}</div></div>)}</div>}
export default function WorkforceApp(){
 const[view,setView]=useState('home'),[requests,setRequests]=useState<Booking[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<string[]>([]),[code,setCode]=useState('AL'),[note,setNote]=useState(''),[modal,setModal]=useState(false),[step,setStep]=useState(0),[running,setRunning]=useState(false),[active,setActive]=useState<string|null>(null),[options,setOptions]=useState<SwapOption[]|null>(null),[response,setResponse]=useState(false),[verified,setVerified]=useState(false),[managerNote,setManagerNote]=useState(''),[focusRequest,setFocusRequest]=useState<string|null>(null),[error,setError]=useState('');
 const cancel=useRef(0);const launchRef=useRef<HTMLButtonElement|null>(null);const dialogRef=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const route=()=>{const h=location.hash.slice(1);setView(({overview:'book',coverage:'manager',planning:'home',workspace:'requests',data:'resources',policies:'resources'} as Record<string,string>)[h]||h||(location.pathname==='/manager'?'manager':'home'))};route();window.addEventListener('hashchange',route);try{const saved=JSON.parse(localStorage.getItem('gimme-workforce-v1')||'[]');if(Array.isArray(saved))setRequests(saved.filter(b=>b.employeeId===me.id&&b.assessment&&Array.isArray(b.events)))}catch{}setLoaded(true);return()=>window.removeEventListener('hashchange',route)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem('gimme-workforce-v1',JSON.stringify(requests))},[requests,loaded]);
 useEffect(()=>{if(!modal)return;dialogRef.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!running)close();if(e.key==='Tab'){const els=dialogRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input,textarea,select,[tabindex="0"]');if(!els?.length)return;const first=els[0],last=els[els.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=old}},[modal,running]);
 const manager=view.startsWith('manager'),current=requests.find(r=>r.id===active),review=requests.find(r=>r.id===focusRequest)||requests.find(r=>r.status==='manager-review')||requests[0];
 const nav=manager?[['manager','Department',Users],['manager-requests','Leave requests',ClipboardList],['manager-resources','Resources',BookOpen]] as const:[['home','My leave',Home],['book','Request leave',CalendarDays],['requests','My requests',ClipboardList],['resources','Resources',BookOpen]] as const;
 const go=(v:string)=>{location.hash=v};
 const patch=(id:string,update:Partial<Booking>,label:string,detail:string)=>setRequests(prev=>prev.map(r=>r.id===id?{...r,...update,events:[...r.events,event(label,detail)]}:r));
 const close=()=>{cancel.current++;setRunning(false);setModal(false);setResponse(false);setTimeout(()=>launchRef.current?.focus(),0)};
 async function start(){setError('');if(!selected.length)return;const overlap=requests.some(r=>!['declined','changes-requested','colleague-declined'].includes(r.status)&&[...r.dates,...(r.swap?.returnShift?[r.swap.returnShift.date]:[])].some(d=>selected.includes(d)));if(overlap){setError('You already have a request for one of these dates. Open My requests to review it.');return}setModal(true);setStep(0);setRunning(true);setActive(null);setOptions(null);const token=++cancel.current;const assessment=assessWithRequests(data,policies,selected,code,requests);for(let i=0;i<assessment.checks.length;i++){setStep(i);await new Promise(r=>setTimeout(r,650));if(token!==cancel.current)return}const id=crypto.randomUUID();const b:Booking={id,employeeId:me.id,leaveCode:code,leaveType:leaveName(code),dates:[...selected].sort(),note,assessment,status:'assessed',swap:null,message:'',managerNote:'',createdAt:now(),events:[event('Request checked','Rules engine v1 · current balance, roster, recorded leave, inferred ANF agreement and MP0187/24. No language model used.'),...assessment.checks.map(c=>event(c.label,`${c.status}: ${c.detail} Source: ${c.source}`))]};setRequests(p=>[b,...p]);setActive(id);setRunning(false);setStep(5)}
 function sendToManager(b:Booking){const submitted=submitForReview(data,policies,b,requests,now());if(!submitted)return;setRequests(prev=>prev.map(r=>r.id===b.id?submitted:r));setResponse(false)}
 function choose(b:Booking,o:SwapOption){patch(b.id,{swap:o,assessment:afterSwap(b.assessment,o),status:'awaiting-colleague',message:`Can you ${o.kind==='swap'?`swap your ${fmt(o.returnShift!.date)} ${o.returnShift!.start}–${o.returnShift!.end} shift for my`:'cover my'} ${fmt(o.outgoing.date)} ${o.outgoing.start}–${o.outgoing.end} shift? ${o.kind==='swap'?'I would take your original shift.':''}`},'Coordination prepared',`${o.employeeId}; ${o.kind}; no external message sent.`);setResponse(false)}
 function decide(b:Booking,status:Booking['status']){if(status==='approved'&&!canApprove(b,verified))return;if(status!=='approved'&&!managerNote.trim())return;patch(b.id,{status,managerNote},statusName(status),managerNote||'Manager confirms patient demand, competencies, staffing requirements and colleague agreement where applicable.');setVerified(false);setManagerNote('')}
 const selectedShifts=shifts.filter(s=>selected.includes(s.date)),hours=round(selectedShifts.reduce((n,s)=>n+s.netHours,0));
 const reserved=(c:string)=>requests.filter(r=>r.leaveCode===c&&!['declined','changes-requested','colleague-declined'].includes(r.status)).reduce((n,r)=>n+r.assessment.hours-(r.swap?.kind==='swap'?r.swap.outgoing.netHours:0),0);
 const requestCards=(isManager=false)=><div className="wf-request-list">{requests.length?requests.map(r=><button className={`wf-request-row ${isManager&&review?.id===r.id?'selected':''}`} key={r.id} onClick={()=>{if(isManager){setFocusRequest(r.id);setVerified(false);setManagerNote('')}else{setActive(r.id);setModal(true);setOptions(null);setRunning(false)}}}><span className="wf-icon"><Leaf size={24}/></span><span><strong>{isManager?'Sarah Chen · ':''}{r.leaveType}</strong><small>{fmt(r.dates[0])} – {fmt(r.dates.at(-1)!)} · {r.assessment.hours-(r.swap?.kind==='swap'?r.swap.outgoing.netHours:0)}h leave{r.swap?.kind==='swap'?' + shift swap':''}</small><small>{r.leaveCode==='AL'&&r.status==='manager-review'?`Response due ${due(r)} · ANF cl33`:statusName(r.status)}</small></span><span className={`wf-pill ${r.status==='approved'?'green':''}`}>{statusName(r.status)}</span><ChevronRight size={18}/></button>):<div className="wf-empty"><ClipboardList size={35}/><h3>No leave requests yet</h3><p>{isManager?'New employee requests will appear here.':'Choose dates from your roster to get started.'}</p>{!isManager&&<button className="wf-primary" onClick={()=>go('book')}>Request leave <ArrowRight size={18}/></button>}</div>}</div>;
 return <div className="wf-app"><header className="wf-top"><a href="#home" className="wf-logo">gimme<span>abreak</span><b>!</b><i>+</i></a><nav aria-label="Main navigation">{nav.map(([id,label,Icon])=><a href={`#${id}`} key={id} className={view===id?'active':''}><Icon size={19}/>{label}</a>)}</nav><button className="wf-switch" onClick={()=>go(manager?'home':'manager')}><Repeat2 size={16}/>{manager?'Employee view':'Clinical manager view'}</button><div className="wf-profile"><span>{manager?'MT':'SC'}</span><div><strong>{manager?'Michael Tan':'Sarah Chen'}</strong><small>{manager?'Clinical Nurse Manager':'Registered Nurse'}</small></div></div></header>
 <main className="wf-main"><section className="wf-hero"><div><span className="wf-eyebrow">{manager?'MANAGER WORKSPACE':'YOUR TIME TO RECHARGE'}</span><h1>{({home:'A little time for you.',book:'Plan your leave',requests:'My requests',manager:'Your department', 'manager-requests':'Team leave',resources:'Resources','manager-resources':'Resources'} as Record<string,string>)[view]||'My leave'}</h1><p>{manager?'Emergency · 21 September – 4 October 2026':view==='home'?'Your leave, your roster, a little breathing room.':view==='book'?'Choose the days you’d like off. We’ll work through the rest.':view==='requests'?'Follow your request, from first check to final decision.':'The data and policies behind your leave checks.'}</p></div><div className="wf-hero-art" aria-hidden="true"><span>Rest. Recharge.<br/>Keep doing good things.</span><div className="wf-sun"/><div className="wf-hill one"/><div className="wf-hill two"/></div></section>
 {view==='home'&&<><div className="wf-section-head"><h2>Your leave balances</h2><small>As at 17 September 2026</small></div><div className="wf-balances">{balances.map((b,i)=><article className={`wf-balance b${i}`} key={b.code}><div><span className="wf-icon">{b.code==='AL'?<Leaf/>:b.code==='PE'?<Heart/>:<Clock/>}</span><span>{leaveName(b.code)}</span></div><strong>{round(b.remainingHours)}<small> hours</small></strong><div className="wf-balance-detail"><span>Accrued <b>{round(b.untakenHours??b.remainingHours)}h</b></span><span>Booked in source <b>{round(b.bookedHours??0)}h</b></span></div>{reserved(b.code)>0&&<small>{round(reserved(b.code))}h in app requests · {round(b.remainingHours-reserved(b.code))}h available after requests</small>}{b.excess&&<span className="wf-pill amber">Leave plan recommended</span>}</article>)}</div><div className="wf-home-grid"><section className="wf-card wf-next"><div className="wf-section-head"><h2><CalendarDays/>Your next fortnight</h2><span className="wf-pill">{shifts.length} shifts · {round(shifts.reduce((n,s)=>n+s.netHours,0))}h</span></div><div className="wf-mini-days">{days.map(d=><div key={d} className={shifts.some(s=>s.date===d)?'on':''}><small>{fmt(d,{weekday:'short'})}</small><b>{fmt(d,{day:'numeric'})}</b><span>{shifts.some(s=>s.date===d)?'●':'–'}</span></div>)}</div><p>Emergency · 21 Sep – 4 Oct</p><button className="wf-primary" onClick={()=>go('book')}>Plan some time off <ArrowRight size={19}/></button></section><section className="wf-card wf-leave-health"><span className="wf-icon"><Heart/></span><h2>Make room for a break</h2><p>Your long service leave is flagged as excess in the balance report. Talk with your manager about a leave plan.</p><a href={policies.documents.find(p=>/Accrued/.test(p.title))?.url} target="_blank" rel="noreferrer">Management of Accrued Leave Policy ↗</a></section></div></>}
 {view==='book'&&<div className="wf-book-grid"><section className="wf-card"><div className="wf-section-head"><h2>21 September – 4 October</h2><span className="wf-pill">Next fortnight</span></div><div className="wf-week-labels">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><span key={d}>{d}</span>)}</div><div className="wf-calendar">{days.map(d=>{const ss=shifts.filter(s=>s.date===d),sel=selected.includes(d);return <button key={d} aria-label={`${fmt(d,{weekday:'long',day:'numeric',month:'long'})}, ${ss.length?'rostered '+ss.map(s=>s.start+' to '+s.end).join(', '):'rostered off'}`} aria-pressed={sel} className={`${ss.length?'duty':'off'} ${sel?'chosen':''}`} onClick={()=>setSelected(p=>p.includes(d)?p.filter(x=>x!==d):[...p,d].sort())}><b>{fmt(d,{day:'numeric'})}{d.endsWith('-01')&&<small> Oct</small>}</b>{sel&&<Check size={17}/>}<span>{ss.length?<><Sun size={18}/>{ss.map(s=><small key={s.id}>{s.start}–{s.end}</small>)}</>:<small>Day off</small>}</span></button>})}</div><div className="wf-legend"><span><i/>Rostered shift</span><span><i/>Day off</span><span><i/>Selected</span></div><details className="wf-details"><summary>View roster details</summary>{shifts.map(s=><div className="wf-line" key={s.id}><b>{fmt(s.date)}</b><span>{s.start}–{s.end} · {s.netHours}h paid · {s.mealMinutes}min break</span></div>)}</details></section><aside className="wf-card wf-selection"><h2><CalendarDays/>Your leave request</h2><div className="wf-selection-summary"><strong>{selected.length?`${fmt(selected[0])} – ${fmt(selected.at(-1)!)}`:'Choose your days'}</strong><span>{selected.length} days selected</span><div><b>{selectedShifts.length}<small>affected shifts</small></b><b>{hours}h<small>leave requested</small></b></div></div><label>Leave type</label><div className="wf-types">{balances.map(b=><button key={b.code} className={code===b.code?'selected':''} onClick={()=>setCode(b.code)}>{b.code==='AL'?<Leaf/>:b.code==='PE'?<Heart/>:<Clock/>}{leaveName(b.code)}</button>)}</div><label htmlFor="leave-note">Note to your manager <small>(optional)</small></label><textarea id="leave-note" value={note} maxLength={300} onChange={e=>setNote(e.target.value)} placeholder="Anything your manager should know"/><small className="wf-count">{note.length}/300</small>{error&&<p role="alert" className="wf-error">{error}</p>}<button ref={launchRef} className="wf-primary" disabled={!selected.length} onClick={start}>Start booking <ArrowRight size={20}/></button><small className="wf-muted">Your manager makes the final decision.</small></aside></div>}
 {view==='requests'&&<section className="wf-card">{requestCards()}</section>}
 {view==='manager'&&<ManagerOverview requests={requests} onRequests={()=>go('manager-requests')}/>}
 {view==='manager-requests'&&<div className="wf-manager-grid"><section className="wf-card"><div className="wf-section-head"><h2>Leave requests</h2><span className="wf-pill">{requests.filter(r=>r.status==='manager-review').length} for review</span></div>{requestCards(true)}</section>{review&&<aside className="wf-card wf-review"><h2>Review leave request</h2><div className="wf-person"><span className="wf-avatar">SC</span><div><strong>Sarah Chen</strong><small>Registered Nurse · Emergency</small></div><span className="wf-pill">{statusName(review.status)}</span></div><div className="wf-selection-summary"><strong>{review.leaveType}</strong><span>{fmt(review.dates[0])} – {fmt(review.dates.at(-1)!)}</span><b>{review.assessment.hours-(review.swap?.kind==='swap'?review.swap.outgoing.netHours:0)}h leave · {review.assessment.shifts.length} shifts affected</b>{review.leaveCode==='AL'&&<small>Response due {due(review)} · ANF cl33(1)</small>}</div>{review.note&&<blockquote>{review.note}</blockquote>}<h3>Impact & coverage</h3>{review.swap?<SwapCard option={review.swap}/>:<p>No colleague cover proposed.</p>}<div className="wf-impact">{review.assessment.shifts.map(s=><div key={s.id}><b>{fmt(s.date)} · {s.start}</b><span>{review.swap?.outgoing.id===s.id?'1 out → 1 in · headcount preserved':'1 rostered position needs review'}</span></div>)}</div><details className="wf-details"><summary>How this was checked</summary><CheckRows checks={review.assessment.checks}/></details>{review.status==='manager-review'?<><label className="wf-confirm"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I have verified patient demand, staffing requirements, competencies and any colleague agreement.</label><label htmlFor="decision-note">Decision reason</label><textarea id="decision-note" value={managerNote} onChange={e=>setManagerNote(e.target.value)} placeholder="Explain operational constraints or conditions"/><button className="wf-primary" disabled={!canApprove(review,verified)} onClick={()=>decide(review,'approved')}><CheckCircle2 size={18}/>Approve request</button><div className="wf-actions"><button disabled={!managerNote.trim()} onClick={()=>decide(review,'changes-requested')}>Request changes</button><button className="danger" disabled={!managerNote.trim()} onClick={()=>decide(review,'declined')}>Decline with reason</button></div><small>A written reason is required for decline or changes.</small></>:<p>{review.managerNote||'This request is not awaiting a manager decision.'}</p>}<details className="wf-details"><summary>Activity history</summary>{review.events.map((e,i)=><div className="wf-timeline" key={i}><strong>{e.label}</strong><small>{new Date(e.at).toLocaleString('en-AU')}</small><p>{e.detail}</p></div>)}</details></aside>}</div>}
 {(view==='resources'||view==='manager-resources')&&<Resources/>}
 </main><footer className="wf-footer"><span><Heart size={17}/>People take better care, when they take a break.</span><a href={manager?'#manager-resources':'#resources'}>Data & policy sources</a></footer>
 {modal&&<div className="wf-overlay"><div className="wf-modal" role="dialog" aria-modal="true" aria-labelledby="agent-title" ref={dialogRef} tabIndex={-1}><div className="wf-modal-top"><span className="wf-icon"><Activity/></span><div><h2 id="agent-title">{running?'Let’s work through your leave':current?.assessment.summary||'Your leave check'}</h2><small>GimmeABreak · roster & policy assistant</small></div><button aria-label="Close leave check" onClick={close}><X/></button></div>
 {running?<div className="wf-thinking" aria-live="polite">{['Checking leave balances','Checking rostered shifts','Checking leave policy','Checking department skill mix','Checking swap requirements'].map((label,i)=><div className={i===step?'current':i<step?'done':''} key={label}>{i<step?<CheckCircle2 size={21}/>:i===step?<LoaderCircle className="wf-spin" size={21}/>:<span className="wf-step-dot"/>}<span>{label}</span>{i===step&&<small>Working…</small>}</div>)}</div>:current&&<><div className="wf-modal-summary"><b>{fmt(current.dates[0])} – {fmt(current.dates.at(-1)!)}</b><span>{current.leaveType} · {current.assessment.hours-(current.swap?.kind==='swap'?current.swap.outgoing.netHours:0)}h leave</span><span className="wf-pill">{statusName(current.status)}</span></div>
 {current.status==='assessed'&&<><CheckRows checks={current.assessment.checks}/>{!current.assessment.checks.some(c=>c.status==='fail'&&c.id!=='balance')&&<>{options===null?<div className="wf-prompt"><h3>{current.assessment.shifts.length?'Would you like me to look for a shift swap?':'Ready to send to your manager?'}</h3><p>{current.assessment.shifts.length?'I’ll check both rosters, leave, hours and rest before suggesting a colleague.':'There are no rostered shifts on your selected dates.'}</p>{current.assessment.shifts.length>0&&<button className="wf-primary" onClick={()=>{setOptions(findAvailableSwaps(data,policies,current.dates,requests,current.id));patch(current.id,{},'Coverage search completed',`Rules v1; compared contracts, rosters and leave. Suggested: ${findAvailableSwaps(data,policies,current.dates,requests,current.id).map(o=>o.employeeId+' '+o.kind).join(', ')||'none'}. Same role/grade, valid contract, no overlap, bilateral rest/hours. Clinical review retained.`)}}><Repeat2 size={18}/>Find a swap or cover</button>}<button className={current.assessment.shifts.length?'wf-secondary':'wf-primary'} disabled={!current.assessment.canProceed} onClick={()=>sendToManager(current)}>Send for manager review <ArrowRight size={18}/></button></div>:<div className="wf-options"><h3>{options.length?'Suggested colleagues':'No compatible colleague found'}</h3><p>{options.length?'Each option covers one affected shift. Your manager reviews any remaining gaps.':'Your manager can consider the casual pool, agency, overtime or a different leave period.'}</p>{options.slice(0,6).map(o=><article className="wf-option" key={o.id}><SwapCard option={o}/><button className="wf-primary" disabled={!afterSwap(current.assessment,o).canProceed} onClick={()=>choose(current,o)}><Send size={17}/>Ask this colleague</button></article>)}<button className="wf-secondary" disabled={!current.assessment.canProceed} onClick={()=>sendToManager(current)}>Send to manager without proposed cover</button></div>}</>}</>}
 {current.status==='awaiting-colleague'&&current.swap&&<><SwapCard option={current.swap}/><h3>Colleague request</h3><blockquote>{current.message}</blockquote><div className="wf-notice"><Send size={18}/><span>Messaging is not connected. You can preview the colleague’s response here; no message has been sent.</span></div>{!response?<button className="wf-primary" onClick={()=>setResponse(true)}>Preview colleague response <ArrowRight size={18}/></button>:<section className="wf-colleague"><span className="wf-eyebrow">COLLEAGUE RESPONSE PREVIEW</span><h3>{name(current.swap.employeeId)}</h3><p>{current.message}</p><div className="wf-actions"><button className="wf-primary" onClick={()=>sendToManager(current)}>I can {current.swap!.kind==='swap'?'swap':'cover'}</button><button onClick={()=>{patch(current.id,{status:'colleague-declined'},'Colleague unavailable (preview)','No agreement; no roster changed.');setResponse(false)}}>I’m unavailable</button></div></section>}</>}
 {current.status==='colleague-declined'&&<><p>The proposed colleague is unavailable. Try another option or ask your manager to review.</p><button className="wf-primary" onClick={()=>{patch(current.id,{status:'assessed',swap:null,assessment:assessWithRequests(data,policies,current.dates,current.leaveCode,requests.filter(r=>r.id!==current.id))},'Finding another option','Previous option was declined.');setOptions(findAvailableSwaps(data,policies,current.dates,requests,current.id).filter(o=>o.employeeId!==current.swap?.employeeId))}}>Try another colleague</button><button className="wf-secondary" disabled={!current.assessment.canProceed} onClick={()=>sendToManager(current)}>Request manager review</button></>}
 {['manager-review','approved','declined','changes-requested'].includes(current.status)&&<><div className="wf-result"><CheckCircle2 size={36}/><h3>{current.status==='manager-review'?'Your request is with the manager':statusName(current.status)}</h3><p>{current.managerNote||(current.swap?'The manager can see the proposed change, checks and remaining staffing questions.':'Your manager can review your leave balance and roster impact.')}</p>{current.leaveCode==='AL'&&current.status==='manager-review'&&<span>Response due {due(current)}</span>}</div>{current.swap&&<SwapCard option={current.swap}/>}<button className="wf-primary" onClick={()=>{close();go('requests')}}>View my requests <ArrowRight size={18}/></button></>}
 <details className="wf-details"><summary>Data used for this request</summary><p>Balance snapshot: {current.assessment.balance?.effectiveDate}. Roster: {current.assessment.shifts.map(s=>s.id.split('#')[1]).join(', ')||'no affected shifts'}. Employee: {me.id}. Agreement inferred from Registered Nurse classification; local applicability requires confirmation.</p><p>Checks run locally with deterministic rules v1. No language model or external messaging service is connected.</p></details></>}
 </div></div>}
 </div>
}
function SwapCard({option:o}:{option:SwapOption}){return <div className="wf-swap"><div className="wf-person"><span className="wf-avatar">RN</span><div><strong>{name(o.employeeId)}</strong><small>Registered Nurse · {data.employees.find(e=>e.id===o.employeeId)?.rate}</small></div><span className="wf-pill green">{o.kind==='swap'?'Shift swap':'Available to ask'}</span></div><div className="wf-swap-grid"><div><small>They take your shift</small><b>{fmt(o.outgoing.date)}</b><span>{o.outgoing.start}–{o.outgoing.end}</span><small>{unitLabel(o.outgoing.unitName)}</small></div><Repeat2 size={22}/><div><small>{o.returnShift?'You take their shift':'Their existing shifts'}</small><b>{o.returnShift?fmt(o.returnShift.date):'Unchanged'}</b><span>{o.returnShift?`${o.returnShift.start}–${o.returnShift.end}`:'No coverage removed'}</span>{o.returnShift&&<small>{unitLabel(o.returnShift.unitName)}</small>}</div></div><div className="wf-inline-checks"><span><Check size={15}/>Same role & grade</span><span><Check size={15}/>No roster or leave conflict</span><span><Check size={15}/>Rest & hours checked</span></div><small>Colleague: {o.candidateHoursBefore} → {o.candidateHoursAfter}h · Your roster: {o.requesterHoursBefore} → {o.requesterHoursAfter}h</small>{o.kind==='swap'&&<small>Swap replaces {o.outgoing.netHours}h of requested leave; those hours stay in your balance.</small>}<small>{o.returnShift&&o.returnShift.unit!==o.outgoing.unit?'Cross-ward swap: competencies in both units and colleague agreement need manager confirmation.':'Clinical suitability and colleague agreement still need confirmation.'}</small></div>}
function ManagerOverview({requests,onRequests}:{requests:Booking[];onRequests:()=>void}){const period=projectedRoster(data,requests).filter(s=>s.unit===data.unit&&s.date>=data.period.start&&s.date<=data.period.end);const ids=new Set(period.map(s=>s.employeeId));const roles=[...new Set(data.employees.filter(e=>ids.has(e.id)).map(e=>e.role))].map(role=>({role,count:data.employees.filter(e=>ids.has(e.id)&&e.role===role).length})).sort((a,b)=>b.count-a.count);return <><div className="wf-stats"><button onClick={onRequests}><ClipboardList/><span>Ready for review<strong>{requests.filter(r=>r.status==='manager-review').length}</strong><small>Awaiting your decision</small></span><ChevronRight/></button><article><Users/><span>Department staff<strong>{ids.size}</strong><small>Rostered this fortnight</small></span></article><article><CalendarDays/><span>Rostered duties<strong>{period.length}</strong><small>After local decisions</small></span></article><article><CheckCircle2/><span>Approved requests<strong>{requests.filter(r=>r.status==='approved').length}</strong><small>In this workspace</small></span></article></div><div className="wf-home-grid"><section className="wf-card"><div className="wf-section-head"><h2><Users/>Fortnight staffing</h2><span className="wf-pill">{requests.some(r=>r.status==='approved')?'After local decisions':'Imported roster'}</span></div><p className="wf-muted">Distinct staff by duty start, including approved local changes. These are not patient-ratio requirements.</p><div className="wf-table-wrap"><table><thead><tr><th>Duty</th>{days.map(d=><th key={d}>{fmt(d,{weekday:'short'})}<small>{fmt(d,{day:'numeric'})}</small></th>)}</tr></thead><tbody>{['Day','Evening','Night'].map((band,i)=><tr key={band}><th>{band}</th>{days.map(d=>{const count=new Set(period.filter(s=>s.date===d&&(Number(s.start.slice(0,2))>=20||Number(s.start.slice(0,2))<6?2:Number(s.start.slice(0,2))>=12?1:0)===i).map(s=>s.employeeId)).size;return <td key={d}><span>{count}</span></td>})}</tr>)}</tbody></table></div><HistoricalContext/><div className="wf-notice"><ShieldCheck size={22}/><span><strong>REQUIRED · Staffing requirement needs verification</strong>Emergency is not automatically covered by the published ward ratio schedule. Patient demand, NHpPD/local rules and skill mix need clinical review.</span></div></section><section className="wf-card"><h2>Department skill mix</h2><p className="wf-muted">People rostered over the fortnight</p>{roles.slice(0,7).map(r=><div className="wf-role" key={r.role}><div><span>{r.role}</span><b>{r.count}</b></div><div><i style={{width:`${r.count/ids.size*100}%`}}/></div></div>)}</section></div><section className="wf-card wf-manager-cta"><div><h2>Keep leave moving</h2><p>Review the request, proposed changes and policy checks together.</p></div><button className="wf-primary" onClick={onRequests}>Open leave requests <ArrowRight size={18}/></button></section></>}
function Resources(){return <div className="wf-resources"><section className="wf-card"><h2><Database/>Connected data</h2><p>All four workforce files were processed. This workspace uses the next-fortnight nursing department and a connected candidate pool. Display names are aliases; source employee and roster IDs remain traceable.</p>{data.sources.map(s=><details key={s.kind} className="wf-details"><summary>{title(s.kind)} <span>{s.rows.toLocaleString()} rows</span></summary><p>{s.fileName}</p><small>{s.columns.join(' · ')}</small></details>)}<div className="wf-notice"><ShieldCheck size={20}/><span>Local rule checks · advisory results · manager decisions. No external model, messaging or payroll connection.</span></div></section><section className="wf-card"><h2><BookOpen/>Policy library</h2><p>Industrial agreement → mandatory staffing policy → local requirements → historical context → suggestions.</p>{policies.documents.map(d=><details key={d.id} className="wf-details"><summary>{d.title}</summary><p>{d.scope}</p>{d.sections.map(s=><div key={s.id}><strong>{s.heading}</strong><p>{s.summary}</p><small>{s.page?`PDF page ${s.page}`:''}</small></div>)}<a href={d.pdfUrl||d.url} target="_blank" rel="noreferrer">Open official source ↗</a></details>)}</section></div>}

function HistoricalContext(){const h=data.historicalStaffing?.filter(h=>h.role==='Registered Nurse'&&h.weekday===1&&h.band==='day')[0];return h?<div className="wf-history"><span className="wf-eyebrow">EXPECTED · RECENT ROSTER CONTEXT</span><h3>{h.min}–{h.max} registered nurses</h3><p>Comparable Monday day duties · median {h.median} · {h.sampleDays} days, {fmt(h.start)}–{fmt(h.end)}</p><small>Descriptive scheduled staffing; never a policy minimum. Historical classifications may be unresolved.</small></div>:null}
