import {requireSession,signValue,verifyValue,secret,sameOrigin,readBody,safeMessage} from '@/server/chat-security';
import {listBookings} from '@/server/chat-store';
import {swapWorkImpact,replyToSwap} from '@/server/swap-coordination';
import {employeeDisplayName} from '@/lib/employee-display';
import raw from '@/data/workforce.json';
import type {Workforce} from '@/lib/workforce-types';
export const runtime='nodejs';export const dynamic='force-dynamic';
function session(req:Request){const s=requireSession(req);if(s.role!=='manager')throw new Error('Manager access required for the Teams preview.');return s}
export async function GET(req:Request){try{const s=session(req),id=new URL(req.url).searchParams.get('requestId');const rows=(await listBookings(s.employeeId)).filter(b=>b.swapInvitation&&(!id||b.id===id));const requests=rows.flatMap(booking=>{const invitation=booking.swapInvitation!,option=invitation.option||booking.swap;if(!option)return [];return[{booking,recipientName:employeeDisplayName(invitation.recipientId,raw as Workforce),impact:swapWorkImpact(option),replyToken:invitation.status==='pending'&&booking.status==='manager-review'?signValue({kind:'teams-preview-reply',employeeId:s.employeeId,requestId:booking.id,invitationId:invitation.id,recipientId:invitation.recipientId,exp:Math.floor(Date.now()/1000)+600},secret()):null}]});return Response.json({requests},{headers:{'Cache-Control':'no-store'}})}catch(e){return Response.json({message:safeMessage(e)},{status:400})}}
export async function POST(req:Request){try{sameOrigin(req);const s=session(req),body=await readBody(req,5000);if(typeof body.token!=='string')throw new Error('Choose a request confirmation card.');const value=verifyValue(body.token,secret());if(!value||value.kind!=='teams-preview-reply'||value.employeeId!==s.employeeId||typeof value.requestId!=='string'||typeof value.invitationId!=='string'||typeof value.recipientId!=='string')throw new Error('This confirmation expired. Refresh the Teams preview.');if(body.status!=='accepted'&&body.status!=='declined')throw new Error('Choose acceptance or decline.');if(body.reason!==undefined&&typeof body.reason!=='string')throw new Error('Provide a short response.');const request=await replyToSwap(s.employeeId,value.requestId,body.status,body.reason||'','teams-preview',value.invitationId,value.recipientId);return Response.json({request})}catch(e){return Response.json({message:safeMessage(e)},{status:400})}}
