'use client';
import { useState } from 'react';
import { AlertTriangle, ArrowRight, CalendarDays, Check, ChevronRight, ClipboardList, Clock3, FileText, LoaderCircle, ShieldCheck, Users, X } from 'lucide-react';
import { demo, simulateCoverage } from '@/lib/gimme-engine';
import { staffName } from '@/lib/staff-display';

type Props = { note: string; complete: boolean; running: boolean; selected: string; decided: boolean; onAnalyse: () => void; onChoose: (id: string) => void; onDecision: () => void };
export default function TeamLeave({ note, complete, running, selected, decided, onAnalyse, onChoose, onDecision }: Props) {
  const [filter, setFilter] = useState('All requests');
  const [open, setOpen] = useState(true);
  const s = demo.scenario;
  const person = s.candidates.find(c => c.employeeId === selected) ?? s.candidates[0];
  const sim = simulateCoverage(person.employeeId);
  const state = decided ? 'Reviewed' : running ? 'Agent working' : complete ? 'Needs attention' : 'Ready for review';
  const visible = filter === 'All requests' || filter === state;
  return <div className={`ref-team ${open ? 'has-review' : ''}`}>
    <div className="ref-team-main">
      <div className="ref-team-stats">{[
        { name: 'Ready for review', value: !complete && !running && !decided ? 1 : 0, sub: 'Awaiting assessment', Icon: ClipboardList },
        { name: 'Needs coverage', value: 1, sub: 'Cover to confirm', Icon: Users },
        { name: 'Needs attention', value: complete && !decided ? 1 : 0, sub: 'Evidence to confirm', Icon: AlertTriangle },
        { name: 'Reviewed', value: decided ? 1 : 0, sub: 'This workspace', Icon: Check },
      ].map(({name,value,sub,Icon}) => <article key={name}><span><Icon size={24}/></span><div><small>{name}</small><strong>{value}</strong><p>{sub}</p></div></article>)}</div>
      <section className="ref-horizon"><div><strong>Next 14 days</strong><p>Assessment status<br/>at a glance</p></div><div className="ref-horizon-days">{Array.from({length:14},(_,i)=>{const date = new Date(2026,8,18+i); const affected = i === 3; return <div key={i} title={affected ? '21 September: replacement cover needed' : 'No assessment available'}><small>{date.toLocaleDateString('en-AU',{weekday:'short'})}</small><span>{date.getDate()} {date.toLocaleDateString("en-AU",{month:"short"})}</span><i className={affected ? 'needs-cover' : ''}/></div>;})}</div><div className="ref-horizon-key"><span><i className="needs-cover"/>Needs cover</span><span><i/>Not assessed</span></div></section>
      <section className="ref-requests"><h2><ClipboardList/>Leave requests</h2><div className="ref-request-tabs">{['All requests','Ready for review','Agent working','Needs attention','Reviewed'].map(item=><button className={filter === item ? 'active' : ''} key={item} onClick={()=>setFilter(item)}>{item}<span>{item === 'All requests' || item === state ? 1 : 0}</span></button>)}</div>
      {visible ? <button className={`ref-request-row ${open ? 'selected' : ''}`} onClick={()=>setOpen(true)}><span className="ref-person-avatar">SC</span><div className="ref-request-person"><strong>Sarah Chen</strong><small>Resident Medical Officer · Clinical Service</small></div><span className="ref-leave-symbol"><CalendarDays size={25}/></span><div className="ref-request-period"><strong>Annual Leave</strong><span>Mon, 21 Sep 2026</span><small>1 rostered day (8 hours)</small></div><div className="ref-request-status"><span>{state}</span><small>{complete ? '2 coverage options' : 'Assessment required'}</small></div><ChevronRight size={21}/></button> : <div className="ref-no-requests"><FileText size={25}/><strong>No requests in this view</strong><p>Choose All requests to return to the current leave request.</p><button onClick={()=>setFilter('All requests')}>View all requests<ArrowRight size={14}/></button></div>}
      <div className="ref-team-note"><ShieldCheck size={18}/><p>Role, availability and contracted hours inform coverage options. Medical specialty and ward context require confirmation. Safety comes first, then equity.</p></div></section>
      <details className="ref-other-cover"><summary>Other ways to arrange cover</summary><p>Discuss reallocation, casual pool, agency or overtime with the rostering team. Availability and cost need confirmation. Cross-role substitution is generally not appropriate; medical specialties are not interchangeable.</p></details>
      <section className="ref-manager-guide"><div><Users size={21}/><h3>A supported team starts with a clear plan.</h3></div><p>Review the request, understand the roster impact, and agree on cover before finalising leave.</p><a href="/#data">See the records behind this request<ArrowRight size={15}/></a></section>
    </div>
    {open && <aside className="ref-review"><div className="ref-review-title"><h2>Review leave request</h2><button aria-label="Close request review" onClick={()=>setOpen(false)}><X size={21}/></button></div><div className="ref-review-person"><span className="ref-person-avatar">SC</span><div><strong>Sarah Chen</strong><small>Resident Medical Officer · Clinical Service</small></div><span className="ref-status">{decided ? 'Reviewed' : 'Decision needed'}</span></div><div className="ref-review-period"><div><CalendarDays/><strong>Annual Leave</strong></div><div><strong>Mon, 21 Sep 2026</strong><span>1 rostered day (8 hours)</span></div></div>
    {note && <blockquote className="ref-personal-note">“{note}”</blockquote>}<h3 className="ref-subtitle"><Users size={21}/>Impact & coverage</h3><div className="ref-impact-grid"><article><strong>Affected shift</strong><div><CalendarDays size={20}/><span>Mon, 21 Sep 2026<br/><small>07:00–15:30 · 8 net hours</small></span></div><p>Emergency Department · RMO</p></article><article><strong>Replacement cover</strong><div className="ref-big-number">8 <span>hours needed</span></div><div className="ref-mini-bar"/><p>{complete ? 'Coverage options available' : 'Waiting for assessment'}</p></article></div>
    {!complete ? <div className="ref-review-start"><ShieldCheck size={28}/><h3>Check the full picture.</h3><p>Review leave balance, roster, policies and available cover before making a decision.</p><button className="ref-primary" onClick={onAnalyse}>{running ? <LoaderCircle size={19} className="spinner"/> : <ClipboardList size={19}/>} {running ? 'View checks in progress' : 'Check this request'}<ArrowRight size={19}/></button></div> : <>
    <div className="ref-cover-option"><div className="ref-cover-title"><Users size={19}/><strong>Proposed coverage option</strong><span>Role matched</span></div><label className="ref-cover-select">Compare clinicians<select value={person.employeeId} disabled={decided} onChange={e=>onChoose(e.target.value)}>{s.candidates.map(c=><option key={c.employeeId} value={c.employeeId}>{staffName(c.employeeId)}</option>)}</select></label><div className="ref-cover-person"><span className="ref-person-avatar alternate">{staffName(person.employeeId).split(' ').map(n=>n[0]).join('')}</span><div><strong>{staffName(person.employeeId)}</strong><small>Resident Medical Officer · {person.rateId}</small></div></div><ul><li><Check/>Same role and rate</li><li><Check/>No detected roster or leave conflict</li><li><Check/>{person.priorUnitShiftCount} scheduled shifts in this unit</li><li><Check/>Current fortnight: {person.currentPayPeriodHours} / {person.contractHours} hours</li><li><Check/>With this shift: {sim.projectedHours} / {person.contractHours} hours</li></ul><button className={selected === person.employeeId ? 'ref-outline' : 'ref-primary'} disabled={decided} onClick={()=>onChoose(person.employeeId)}>{selected === person.employeeId ? <><Check size={18}/>Selected for review</> : <>Select coverage option<ArrowRight size={18}/></>}</button></div>
    <div className="ref-review-warning"><AlertTriangle size={19}/><div><strong>Four checks still need confirmation</strong><p>Leave balance, safe staffing, fatigue, credentials and medical specialty.</p><a href="/#policies">Review evidence<ArrowRight size={13}/></a></div></div><button className="ref-primary" disabled={decided} onClick={onDecision}><ShieldCheck size={18}/>{decided ? 'Decision recorded' : 'Review and record decision'}<ArrowRight size={18}/></button></>}
    </aside>}
  </div>;
}
